export const eventsData = [
  {
    icon: "🏎️💨",
    title: "Rally",
    time: "7:30 AM – 8:00 AM",
    angle: 0,
    gradient: "gradient-orange",
    description: "Rally to start the freshers' day.",
    venue: "College Campus",
    coordinator: "Srijan ,Madan",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🏛️",
    title: "In Front of the College",
    time: "8:00 AM – 8:20 AM",
    angle: 30,
    gradient: "gradient-purple",
    description: "Gather and brief students in front of the college.",
    venue: "College Front Gate",
    coordinator: "Nishanth, Chinmay",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "💥",
    title: "Flash Mob & Banner Launch",
    time: "8:20 AM – 8:45 AM",
    angle: 60,
    gradient: "gradient-coral",
    description: "Flash mob performance and official banner launch.",
    venue: "College Campus",
    coordinator: "Vishal, Krishna,Chaithanya",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🚌",
    title: "Transportation to the Hall",
    time: "8:45 AM – 9:15 AM",
    angle: 90,
    gradient: "gradient-pink",
    description: "Move participants from campus to event hall.",
    venue: "Campus to Event Hall",
    coordinator: "Yuvaraj, Hazeez",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🎉",
    title: "Welcoming the Freshers",
    time: "9:15 AM – 9:45 AM",
    angle: 120,
    gradient: "gradient-pink-light",
    description: "Official welcome and short speeches by 3rd year team.",
    venue: "Event Hall",
    coordinator: "Gouthami, Likhitha, Janani, Swathi",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🎭",
    title: "Cultural Events (Morning)",
    time: "9:45 AM – 10:30 AM",
    angle: 150,
    gradient: "gradient-pink-purple",
    description:
      "Group Dance (2nd year A — 5 mins) • Solo Song (2nd year A — 3 mins) • Dialogue performance with different emotions (15–20 members — 15 mins) • Group Dance (2nd year C — 5 mins)",
    venue: "Event Hall Stage",
    coordinator: "Brunda, Rithika",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🎓",
    title: "Formal Function",
    time: "10:30 AM – 12:00 PM",
    angle: 180,
    gradient: "gradient-red",
    description: "Official addresses, awards, and guest speeches.",
    venue: "Event Hall",
    coordinator: "Jnanasiri, Karthika, Thrishali",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🎪",
    title: "Cultural Events (Midday)",
    time: "12:00 PM – 12:45 PM",
    angle: 210,
    gradient: "gradient-purple-dark",
    description:
      "Biscuit Game (15 members — 15 mins) • Group Dance (3rd year A — 3 mins) • You Make the Face I Make the Sound (15 members — 15 mins) • Group song (3rd year B — 3 mins)",
    venue: "Event Hall Stage",
    coordinator: "Nandan, Pranamya",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🍽️",
    title: "Lunch Break",
    time: "12:45 PM – 1:30 PM",
    angle: 240,
    gradient: "gradient-red-pink",
    description: "Lunch for participants and guests.",
    venue: "Dining Hall",
    coordinator: "Rakshith, Darshan Alva",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🎨",
    title: "Cultural Events (Afternoon)",
    time: "1:30 PM – 4:15 PM",
    angle: 270,
    gradient: "gradient-teal",
    description:
      "Solo song by Abdul Hazeez (4th year — 5 mins) • Balloon Blasting (20 members — 10 mins) • Group Dance (3rd year B — Girls — 4 mins) • Group song by Thrishali and Pooja (4th year — 4 mins) • Freeze Dance (15 members — 10 mins) • Solo Dance by Sadhana (3rd year — 4 mins) • Group Dance (3rd year A — Boys — 5 mins) • Saree Draping (20 members — 15 mins) • Group Dance by Nayana and team (4th year — 4.30 mins) • Solo song by Apeksha (4th year — 3 mins) • Blindfold Makeup (16–18 members — 15 mins) • Group Dance by Priya and team (4th year — 5 mins) • Solo song by BharathRaj (4th year — 5 mins) • Reverse order Challenge (15 members — 10 mins) • Group Dance by Team Unique (4th year — 3 mins) • Solo song by Thrishali (4th year — 4 mins) • Group Dance by CS Girls (4th year — 3 mins) • Pass the Balloon (20 members — 15 mins) • Solo Song by Pooja (4th year — 3 mins) • Powder and card (30 members — 20 mins) • Group Dance by 4th year boys (5 mins)",
    venue: "Event Hall Stage",
    coordinator: "Shanmukha, Jyothika",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "☕",
    title: "Tea Break",
    time: "4:15 PM – 4:30 PM",
    angle: 300,
    gradient: "gradient-yellow",
    description: "Short refreshment break.",
    venue: "Refreshment Area",
    coordinator: "Amarjith, Prajwal",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
  {
    icon: "🥁",
    title: "Water Drums",
    time: "4:30 PM – 6:00 PM",
    angle: 330,
    gradient: "gradient-blue",
    description: "Closing performance / Water drums finale.",
    venue: "Event Hall Stage",
    coordinator: "Srijan, Chethan Kumar",
    coordinatorEmail: "events@college.edu",
    coordinatorPhone: "Contact: TBD",
  },
];
